#!/usr/bin/env python3
"""Emit the Erdos647Sparse 10^13 chunk certificates, driver, and root module.

Reads witnesses_1e13.jsonl (verified by verify_coverage_1e13.py), partitions
by grid index j = n / 360360 into spans of CHUNK j-values, and writes into
the decanus checkout:

  Erdos647Sparse/Chunks13/ChunkNNNN.lean  one sparseOk13 decide per chunk
  Erdos647Sparse/Grid13.lean              composed driver grid13_killed
  Erdos647Sparse.lean                     root import module (now includes
                                          the 10^12 AND 10^13 certificates)

Existing 10^12 modules (Chunks/, Grid.lean, Headline.lean) are untouched so
their Lake cache stays valid. Do not edit the generated files by hand.
"""

import json
import os

M = 360360
J0, J1 = 2775003, 27750027  # (1e12, 1e13]
CHUNK = 16384
HERE = os.path.dirname(os.path.abspath(__file__))
DEC = os.environ.get("ERDOS647_SPARSE_ROOT", os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))  # package root (holds Erdos647Sparse/)

HEADER = """/-
Generated by scripts/emit_sparse_lean13.py from a doubly-verified witness
list (Fjordmind Labs (Eero Tölö), 2026-10-02). Do not edit by hand.
-/
"""


def fmt_witness(w):
    pairs = ",".join(f"({p},{e})" for p, e in w["pairs"])
    return f"  ({w['k']},[{pairs}])"


def main():
    with open(os.path.join(HERE, "witnesses_1e13.jsonl")) as f:
        ws = [json.loads(line) for line in f]
    for w in ws:
        assert w["n"] % M == 0
        w["j"] = w["n"] // M
    assert ws[0]["j"] >= J0 and ws[-1]["j"] <= J1

    os.makedirs(os.path.join(DEC, "Erdos647Sparse", "Chunks13"), exist_ok=True)

    chunks = []  # (idx, j_start, fuel, n_witnesses)
    wi = 0
    idx = 0
    j = J0
    while j <= J1:
        fuel = min(CHUNK, J1 + 1 - j)
        sel = []
        while wi < len(ws) and ws[wi]["j"] < j + fuel:
            sel.append(ws[wi])
            wi += 1
        name = f"Chunk{idx:04d}"
        body = ",\n".join(fmt_witness(w) for w in sel)
        src = (
            HEADER
            + "import Erdos647Sparse.Checker13\n\n"
            + "namespace Erdos647Sparse.Chunks13\n\n"
            + "set_option maxRecDepth 1000000\n"
            + "set_option maxHeartbeats 0\n\n"
            + f"def ws{idx:04d} : List (ℕ × Erdos647.Pairs) := [\n{body}]\n\n"
            + f"theorem chunk{idx:04d}_ok : sparseOk13 {fuel} {j} ws{idx:04d} = true := by decide\n\n"
            + "end Erdos647Sparse.Chunks13\n"
        )
        with open(os.path.join(DEC, "Erdos647Sparse", "Chunks13", name + ".lean"), "w") as f:
            f.write(src)
        chunks.append((idx, j, fuel, len(sel)))
        j += fuel
        idx += 1
    assert wi == len(ws), f"{len(ws) - wi} witnesses unassigned"

    # Driver: grid13_killed via by_cases ladder over chunk spans.
    lines = [HEADER]
    for i, _, _, _ in chunks:
        lines.append(f"import Erdos647Sparse.Chunks13.Chunk{i:04d}")
    lines += [
        "",
        "set_option maxRecDepth 1000000",
        "set_option maxHeartbeats 0",
        "",
        "namespace Erdos647Sparse",
        "",
        "open Erdos647 (Killed)",
        "",
        f"/-- Every surviving grid point `360360 * j` with `{J0} ≤ j ≤ {J1}`",
        "(i.e. every rung-4 sieve survivor in `(10^12, 10^13]`) is killed. -/",
        f"theorem grid13_killed (j : ℕ) (h1 : {J0} ≤ j) (h2 : j ≤ {J1})",
        "    (hf : gridFilter13 (360360 * j) = true) : Killed (360360 * j) := by",
    ]
    for i, (idx, js, fuel, _) in enumerate(chunks):
        app = (
            f"exact sparseOk13_sound Chunks13.chunk{idx:04d}_ok j (by omega) (by omega) hf"
        )
        if i < len(chunks) - 1:
            lines.append(f"  by_cases h{idx} : j < {js + fuel}")
            lines.append(f"  · {app}")
        else:
            lines.append(f"  {app}")
    lines += ["", "end Erdos647Sparse", ""]
    with open(os.path.join(DEC, "Erdos647Sparse", "Grid13.lean"), "w") as f:
        f.write("\n".join(lines))

    # Root module: 10^12 chain + 10^13 chain.
    with open(os.path.join(DEC, "Erdos647Sparse.lean"), "w") as f:
        f.write(HEADER + "import Erdos647Sparse.Mod\nimport Erdos647Sparse.Checker\n"
                + "import Erdos647Sparse.Grid\nimport Erdos647Sparse.Headline\n"
                + "import Erdos647Sparse.Checker13\nimport Erdos647Sparse.Grid13\n"
                + "import Erdos647Sparse.Headline13\n")

    tot = sum(c[3] for c in chunks)
    print(f"{len(chunks)} chunks, {tot} witnesses, j in [{J0}, {J1}]")
    for idx, js, fuel, nw in chunks[:3] + chunks[-2:]:
        print(f"  Chunk{idx:04d}: j {js}..{js + fuel - 1}, {nw} witnesses")


if __name__ == "__main__":
    main()
