#!/usr/bin/env python3
"""Emit the Erdos647Sparse chunk certificates, driver, and root module.

Reads witnesses_low.jsonl + witnesses_rung3.jsonl (verified by
verify_coverage_1e11.py), partitions by grid index j = n / 360360 into
spans of CHUNK j-values, and writes into the decanus checkout:

  Erdos647Sparse/Chunks/ChunkNNNN.lean   one sparseOk decide per chunk
  Erdos647Sparse/Grid.lean               composed driver grid_killed
  Erdos647Sparse.lean                    root import module

Do not edit the generated files by hand.
"""

import json
import os

M = 360360
J0, J1 = 28, 2775002  # (1e7, 1e12]
CHUNK = 4096
HERE = os.path.dirname(os.path.abspath(__file__))
DEC = os.environ.get("ERDOS647_SPARSE_ROOT", os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))  # package root (holds Erdos647Sparse/)

HEADER = """/-
Generated by scripts/emit_sparse_lean.py from a doubly-verified witness
list (Fjordmind Labs (Eero Tölö), 2026-10-02). Do not edit by hand.
-/
"""


def load(fn):
    with open(os.path.join(HERE, fn)) as f:
        return [json.loads(line) for line in f]


def fmt_witness(w):
    pairs = ",".join(f"({p},{e})" for p, e in w["pairs"])
    return f"  ({w['k']},[{pairs}])"


def main():
    ws = (load("witnesses_low.jsonl") + load("witnesses_rung3.jsonl")
          + load("witnesses_1e12.jsonl"))
    for w in ws:
        assert w["n"] % M == 0
        w["j"] = w["n"] // M
    assert ws[0]["j"] >= J0 and ws[-1]["j"] <= J1

    os.makedirs(os.path.join(DEC, "Erdos647Sparse", "Chunks"), exist_ok=True)

    chunks = []  # (idx, j_start, fuel, n_witnesses)
    wi = 0
    idx = 0
    j = J0
    while j <= J1:
        fuel = min(CHUNK, J1 + 1 - j)
        sel = []
        while wi < len(ws) and ws[wi]["j"] < j + fuel:
            sel.append(ws[wi])
            wi += 1
        name = f"Chunk{idx:04d}"
        body = ",\n".join(fmt_witness(w) for w in sel)
        src = (
            HEADER
            + "import Erdos647Sparse.Checker\n\n"
            + "namespace Erdos647Sparse.Chunks\n\n"
            + "set_option maxRecDepth 1000000\n"
            + "set_option maxHeartbeats 0\n\n"
            + f"def ws{idx:04d} : List (ℕ × Erdos647.Pairs) := [\n{body}]\n\n"
            + f"theorem chunk{idx:04d}_ok : sparseOk {fuel} {j} ws{idx:04d} = true := by decide\n\n"
            + "end Erdos647Sparse.Chunks\n"
        )
        with open(os.path.join(DEC, "Erdos647Sparse", "Chunks", name + ".lean"), "w") as f:
            f.write(src)
        chunks.append((idx, j, fuel, len(sel)))
        j += fuel
        idx += 1
    assert wi == len(ws), f"{len(ws) - wi} witnesses unassigned"

    # Driver: grid_killed via by_cases ladder over chunk spans.
    lines = [HEADER]
    for i, _, _, _ in chunks:
        lines.append(f"import Erdos647Sparse.Chunks.Chunk{i:04d}")
    lines += [
        "",
        "set_option maxRecDepth 1000000",
        "set_option maxHeartbeats 0",
        "",
        "namespace Erdos647Sparse",
        "",
        "open Erdos647 (Killed)",
        "",
        "/-- Every surviving grid point `360360 * j` with `28 ≤ j ≤ 2775002`",
        "(i.e. every sieve survivor in `(10^7, 10^12]`) is killed. -/",
        "theorem grid_killed (j : ℕ) (h1 : 28 ≤ j) (h2 : j ≤ 2775002)",
        "    (hf : gridFilter (360360 * j) = true) : Killed (360360 * j) := by",
    ]
    for i, (idx, js, fuel, _) in enumerate(chunks):
        app = (
            f"exact sparseOk_sound Chunks.chunk{idx:04d}_ok j (by omega) (by omega) hf"
        )
        if i < len(chunks) - 1:
            lines.append(f"  by_cases h{idx} : j < {js + fuel}")
            lines.append(f"  · {app}")
        else:
            lines.append(f"  {app}")
    lines += ["", "end Erdos647Sparse", ""]
    with open(os.path.join(DEC, "Erdos647Sparse", "Grid.lean"), "w") as f:
        f.write("\n".join(lines))

    # Root module.
    with open(os.path.join(DEC, "Erdos647Sparse.lean"), "w") as f:
        f.write(HEADER + "import Erdos647Sparse.Mod\nimport Erdos647Sparse.Checker\n"
                + "import Erdos647Sparse.Grid\nimport Erdos647Sparse.Headline\n")

    tot = sum(c[3] for c in chunks)
    print(f"{len(chunks)} chunks, {tot} witnesses, j in [{J0}, {J1}]")
    for idx, js, fuel, nw in chunks[:3] + chunks[-2:]:
        print(f"  Chunk{idx:04d}: j {js}..{js + fuel - 1}, {nw} witnesses")


if __name__ == "__main__":
    main()
