#!/usr/bin/env python3
"""Erdős #647 10^13: re-emit Grid13.lean as a balanced binary-split driver.

The linear by_cases ladder (1,525 branches) accumulates every negated
hypothesis in the omega context, so elaboration cost/memory grow
quadratically with the chunk count. This emitter replaces it with one tiny
lemma per chunk span plus a balanced tree of pairwise merges, each with an
O(1) omega context. The statement of `grid13_killed` is unchanged.

Reads the chunk spans from the existing Chunks13/ChunkNNNN.lean files
(`theorem chunkNNNN_ok : sparseOk13 FUEL JS wsNNNN = true`), so it is
independent of the witness data and can be run without regenerating chunks.
"""

import os
import re
import sys

DEC = os.environ.get("ERDOS647_SPARSE_ROOT", os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))  # package root (holds Erdos647Sparse/)
CH = os.path.join(DEC, "Erdos647Sparse", "Chunks13")
J0, J1 = 2775003, 27750027

HEADER = """/-
Generated by scripts/emit_grid13_tree.py (balanced binary-split driver)
from the verified chunk spans (Fjordmind Labs (Eero Tölö), 2026-10-03).
Do not edit by hand.
-/
"""

spans = []  # (idx, js, fuel)
pat = re.compile(r"theorem chunk(\d{4})_ok : sparseOk13 (\d+) (\d+) ws\d{4} = true")
for name in sorted(os.listdir(CH)):
    if not name.endswith(".lean"):
        continue
    with open(os.path.join(CH, name)) as f:
        m = pat.search(f.read())
    assert m, name
    spans.append((int(m.group(1)), int(m.group(3)), int(m.group(2))))
spans.sort()
assert spans[0][1] == J0, spans[0]
for (a, js, fuel), (b, js2, _) in zip(spans, spans[1:]):
    assert b == a + 1 and js2 == js + fuel, (a, js, fuel, b, js2)
assert spans[-1][1] + spans[-1][2] == J1 + 1, spans[-1]
print(f"{len(spans)} contiguous chunk spans, j in [{J0}, {J1}]")

lines = [HEADER]
for idx, _, _ in spans:
    lines.append(f"import Erdos647Sparse.Chunks13.Chunk{idx:04d}")
lines += ["", "set_option maxRecDepth 1000000", "set_option maxHeartbeats 0", "",
          "namespace Erdos647Sparse", "", "open Erdos647 (Killed)", ""]

# Leaves: span lemma per chunk, half-open [lo, hi).
nodes = []  # (name, lo, hi)
for idx, js, fuel in spans:
    name = f"span{idx:04d}"
    lines += [
        f"theorem {name} (j : ℕ) (h1 : {js} ≤ j) (h2 : j < {js + fuel})",
        "    (hf : gridFilter13 (360360 * j) = true) : Killed (360360 * j) :=",
        f"  sparseOk13_sound Chunks13.chunk{idx:04d}_ok j h1 h2 hf",
        "",
    ]
    nodes.append((name, js, js + fuel))

# Balanced merge tree.
level = 0
while len(nodes) > 1:
    nxt = []
    for i in range(0, len(nodes), 2):
        if i + 1 == len(nodes):
            nxt.append(nodes[i])
            continue
        (na, lo, mid), (nb, mid2, hi) = nodes[i], nodes[i + 1]
        assert mid == mid2
        name = f"m{level}_{i // 2:04d}"
        lines += [
            f"theorem {name} (j : ℕ) (h1 : {lo} ≤ j) (h2 : j < {hi})",
            "    (hf : gridFilter13 (360360 * j) = true) : Killed (360360 * j) := by",
            f"  by_cases h : j < {mid}",
            f"  · exact {na} j h1 h hf",
            f"  · exact {nb} j (by omega) h2 hf",
            "",
        ]
        nxt.append((name, lo, hi))
    nodes = nxt
    level += 1

root, lo, hi = nodes[0]
assert lo == J0 and hi == J1 + 1
lines += [
    f"/-- Every surviving grid point `360360 * j` with `{J0} ≤ j ≤ {J1}`",
    "(i.e. every rung-4 sieve survivor in `(10^12, 10^13]`) is killed. -/",
    f"theorem grid13_killed (j : ℕ) (h1 : {J0} ≤ j) (h2 : j ≤ {J1})",
    "    (hf : gridFilter13 (360360 * j) = true) : Killed (360360 * j) :=",
    f"  {root} j h1 (by omega) hf",
    "", "end Erdos647Sparse", "",
]

out = os.path.join(DEC, "Erdos647Sparse", "Grid13.lean")
if "--dry-run" in sys.argv:
    out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "Grid13_tree_preview.lean")
with open(out, "w") as f:
    f.write("\n".join(lines))
print(f"wrote {out}: {len(spans)} leaves, {level} merge levels, root {root}")
