#!/usr/bin/env python3
"""Emit the rung-4 Lean chunks and driver from rung4_certs.json.

Outputs (into the decanus checkout):
  Erdos647Sparse/Rung4Chunks/ChunkNN.lean  — span walk certs, one decide each
  Erdos647Sparse/Rung4.lean                — survivors4, composed soundness,
                                             pairIdxOf, classOk4, final theorem
"""

import json, os

HERE = os.path.dirname(os.path.abspath(__file__))
DECANUS = os.environ.get("ERDOS647_SPARSE_ROOT", os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))  # package root (holds Erdos647Sparse/)
CHUNK = 1000
TOTAL = 41 * 23 * 29  # 27347

SURVIVORS_1719 = [
    (0, 0), (0, 7), (0, 11), (0, 13), (0, 14), (0, 15),
    (0, 16), (0, 17), (11, 0), (11, 13), (11, 14), (11, 15),
    (11, 16), (11, 17), (13, 0), (13, 7), (13, 14), (13, 15),
    (13, 16), (13, 17), (14, 0), (14, 7), (14, 11), (14, 13),
    (14, 15), (14, 16), (14, 17), (15, 0), (15, 7), (15, 11),
    (15, 13), (15, 14), (15, 16), (15, 17), (16, 0), (16, 7),
    (16, 11), (16, 13), (16, 14), (16, 15), (16, 17),
]

with open(os.path.join(HERE, "rung4_certs.json")) as f:
    data = json.load(f)
SS, KS = data["survivors"], data["kills"]

os.makedirs(os.path.join(DECANUS, "Erdos647Sparse/Rung4Chunks"), exist_ok=True)


def fmt_pairs(ps):
    return "[" + ", ".join(f"({p}, {e})" for p, e in ps) + "]"


def fmt_list(xs, per_line=18):
    lines = []
    for a in range(0, len(xs), per_line):
        lines.append(", ".join(str(x) for x in xs[a:a + per_line]))
    return "[" + ",\n   ".join(lines) + "]"


n_chunks = (TOTAL + CHUNK - 1) // CHUNK
chunk_meta = []
for c in range(n_chunks):
    i0, i1 = c * CHUNK, min((c + 1) * CHUNK, TOTAL)
    fuel = i1 - i0
    ss_c = [i for i in SS if i0 <= i < i1]
    ks_c = [(i, k, ps) for i, k, ps in KS if i0 <= i < i1]
    assert len(ss_c) + len(ks_c) == fuel
    certs = ",\n   ".join(f"({k}, {fmt_pairs(ps)})" for _, k, ps in ks_c)
    body = f"""/-
Rung-4 class-kill chunk {c:02d}: flat indices [{i0}, {i1}).
Generated by scripts/emit_rung4_lean.py — do not edit by hand.
-/
import Erdos647Sparse.Rung4Checker

namespace Erdos647Sparse

def rung4Ss{c:02d} : List ℕ :=
  {fmt_list(ss_c)}

def rung4Ks{c:02d} : List (ℕ × Erdos647.Pairs) :=
  [{certs}]

set_option maxRecDepth 8000 in
theorem rung4Walk{c:02d} : rung4Walk {fuel} {i0} rung4Ss{c:02d} rung4Ks{c:02d} = true := by
  decide

end Erdos647Sparse
"""
    with open(os.path.join(DECANUS, f"Erdos647Sparse/Rung4Chunks/Chunk{c:02d}.lean"), "w") as f:
        f.write(body)
    chunk_meta.append((c, i0, i1))
print(f"{n_chunks} chunks written")

# ---- driver ----
imports = "\n".join(
    f"import Erdos647Sparse.Rung4Chunks.Chunk{c:02d}" for c, _, _ in chunk_meta)

# killed_or_surv: span ladder. Membership in the appended survivor list is
# an O(1) proof term: mem_append_right into the chunk, mem_append_left over
# the suffix (concat is left-associated).
ladder = []
last = n_chunks - 1
for c, i0, i1 in chunk_meta:
    inner = "hm" if c == 0 else "(List.mem_append_right _ hm)"
    embed = "(List.mem_append_left _ " * (last - c) + inner + ")" * (last - c)
    ladder.append(f"""  by_cases h{c:02d} : i < {i1}
  · rcases rung4Walk_sound rung4Walk{c:02d} i (by omega) (by omega) with hm | hk
    · exact Or.inl {embed}
    · exact Or.inr hk""")
ladder_txt = "\n".join(ladder)

subs = ""

# pairIdxOf + pairAt consistency, and the 41 resolve cases
pidx_cases = "\n".join(
    f"  | {a}, {b} => {idx}" for idx, (a, b) in enumerate(SURVIVORS_1719))
resolve_cases = []
for idx, (a, b) in enumerate(SURVIVORS_1719):
    resolve_cases.append(
        f"""  · rw [Prod.mk.injEq] at h
    exact rung4_resolve (p := {idx}) hn H hL (by omega) rfl rfl h.1 h.2""")
resolve_txt = "\n".join(resolve_cases)
pipes = "|".join(["h"] * 41)

driver = f"""/-
Erdős #647 rung 4 driver: mod 23·29 sieve theorem.
Generated by scripts/emit_rung4_lean.py — do not edit by hand.

`classOk4_of_cand`: every candidate n > 10^11 has its residue class
(n % 17, n % 19, n % 23, n % 29), flat-encoded, among the {len(SS)} rung-4
survivors. The {len(KS)} killed classes are certified in Rung4Chunks/.
-/
{imports}

namespace Erdos647Sparse

set_option maxRecDepth 100000
set_option maxHeartbeats 4000000

/-- The {len(SS)} rung-4 survivor classes, flat-encoded:
`i = (pairIdx * 23 + c23) * 29 + c29` over the 41 rung-2b pairs. -/
def rung4Survivors : List ℕ :=
  rung4Ss00{"".join(f" ++ rung4Ss{c:02d}" for c in range(1, n_chunks))}

{subs}

/-- Composed walk soundness: every flat class index is a listed survivor
or a killed class. -/
theorem rung4_killed_or_surv :
    ∀ i : ℕ, i < {TOTAL} → i ∈ rung4Survivors ∨ KilledClass i := by
  intro i hi
{ladder_txt}
  · omega

/-- Index of a rung-2b survivor pair; 41 for non-survivors (never hit on
candidates). Inverse of `pairAt` on the survivor range. -/
def pairIdxOf : ℕ → ℕ → ℕ
{pidx_cases}
  | _, _ => 41

/-- The rung-4 class filter: the flat-encoded residue class of `n` is a
rung-4 survivor. -/
def classOk4 (n : ℕ) : Bool :=
  inIdx ((pairIdxOf (n % 17) (n % 19) * 23 + n % 23) * 29 + n % 29) rung4Survivors

private theorem rung4_resolve {{n p c17 c19 : ℕ}} (hn : 100000000000 < n)
    (H : Erdos647Mod.Cand n) (hL : 360360 ∣ n) (hp41 : p < 41)
    (hpa : pairAt p = (c17, c19)) (hpi : pairIdxOf c17 c19 = p)
    (h17 : n % 17 = c17) (h19 : n % 19 = c19) : classOk4 n = true := by
  have h23 : n % 23 < 23 := Nat.mod_lt _ (by norm_num)
  have h29 : n % 29 < 29 := Nat.mod_lt _ (by norm_num)
  rw [classOk4, h17, h19, hpi]
  rcases rung4_killed_or_surv ((p * 23 + n % 23) * 29 + n % 29) (by omega) with hm | hk
  · exact inIdx_of_mem hm
  · exfalso
    have e1 : ((p * 23 + n % 23) * 29 + n % 29) / 667 = p := by omega
    have e2 : ((p * 23 + n % 23) * 29 + n % 29) % 667 / 29 = n % 23 := by omega
    have e3 : ((p * 23 + n % 23) * 29 + n % 29) % 29 = n % 29 := by omega
    exact hk n hn H hL
      (by rw [e1, hpa]; exact h17) (by rw [e1, hpa]; exact h19)
      (by rw [e2]) (by rw [e3])

set_option maxHeartbeats 1600000 in
/-- **Rung 4 headline.** Every candidate `n > 10^11` has its residue class
mod 17·19·23·29 among the {len(SS)} rung-4 survivors. -/
theorem classOk4_of_cand {{n : ℕ}} (hn : 100000000000 < n)
    (H : Erdos647Mod.Cand n) : classOk4 n = true := by
  have hL : 360360 ∣ n := Erdos647Mod.mod360360_of_cand (by omega) H
  have hp := Erdos647Mod.mod_17_19_of_cand (by omega) H
  simp only [Erdos647Mod.survivors, List.mem_cons, List.not_mem_nil, or_false] at hp
  rcases hp with {pipes}
{resolve_txt}

end Erdos647Sparse
"""
with open(os.path.join(DECANUS, "Erdos647Sparse/Rung4.lean"), "w") as f:
    f.write(driver)
print("driver written: Erdos647Sparse/Rung4.lean")
