#!/usr/bin/env python3
"""Emit Erdos647Sparse/Masks13.lean: the two filter bitmasks as Nat literals.

mask323: bit r (r < 323) set iff (r % 17, r % 19) is a rung-2b survivor.
mask27k: bit i (i < 27347) set iff i is a rung-4 flat survivor class.
Sources double-verified in filter13.py (Lean chunk extraction vs JSON).
"""

import os

from filter13 import MASK323, MASK27K

DEC = os.environ.get("ERDOS647_SPARSE_ROOT", os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))  # package root (holds Erdos647Sparse/)

SRC = f"""/-
Generated by scripts/emit_masks13.py from the doubly-verified rung-2b and
rung-4 survivor lists (Fjordmind Labs (Eero Tölö), 2026-10-02). Do not
edit by hand. Bridge lemmas tying these to classOk/classOk4 live in
Erdos647Sparse/Checker13.lean.
-/

namespace Erdos647Sparse

/-- Bit `r` (`r < 323`) is set iff `(r % 17, r % 19)` is one of the 41
rung-2b survivor pairs. -/
def mask323 : Nat := 0x{MASK323:x}

/-- Bit `i` (`i < 27347`) is set iff flat class `i` is one of the 4431
rung-4 survivors (`rung4Survivors`). -/
def mask27k : Nat := 0x{MASK27K:x}

end Erdos647Sparse
"""

with open(os.path.join(DEC, "Erdos647Sparse", "Masks13.lean"), "w") as f:
    f.write(SRC)
print("wrote Masks13.lean:", len(SRC), "bytes")
