/-
Generated by scripts/emit_sparse_lean13.py from a doubly-verified witness
list (Fjordmind Labs, Eero Tölö, 2026-10). Do not edit by hand.
-/
import Erdos647Sparse.Mod
import Erdos647Sparse.Checker
import Erdos647Sparse.Grid
import Erdos647Sparse.Headline
import Erdos647Sparse.Checker13
import Erdos647Sparse.Grid13
import Erdos647Sparse.Headline13
