/-
Erdős #647 rung 4 driver: mod 23·29 sieve theorem.
Generated by scripts/emit_rung4_lean.py — do not edit by hand.

`classOk4_of_cand`: every candidate n > 10^11 has its residue class
(n % 17, n % 19, n % 23, n % 29), flat-encoded, among the 4431 rung-4
survivors. The 22916 killed classes are certified in Rung4Chunks/.
-/
import Erdos647Sparse.Rung4Chunks.Chunk00
import Erdos647Sparse.Rung4Chunks.Chunk01
import Erdos647Sparse.Rung4Chunks.Chunk02
import Erdos647Sparse.Rung4Chunks.Chunk03
import Erdos647Sparse.Rung4Chunks.Chunk04
import Erdos647Sparse.Rung4Chunks.Chunk05
import Erdos647Sparse.Rung4Chunks.Chunk06
import Erdos647Sparse.Rung4Chunks.Chunk07
import Erdos647Sparse.Rung4Chunks.Chunk08
import Erdos647Sparse.Rung4Chunks.Chunk09
import Erdos647Sparse.Rung4Chunks.Chunk10
import Erdos647Sparse.Rung4Chunks.Chunk11
import Erdos647Sparse.Rung4Chunks.Chunk12
import Erdos647Sparse.Rung4Chunks.Chunk13
import Erdos647Sparse.Rung4Chunks.Chunk14
import Erdos647Sparse.Rung4Chunks.Chunk15
import Erdos647Sparse.Rung4Chunks.Chunk16
import Erdos647Sparse.Rung4Chunks.Chunk17
import Erdos647Sparse.Rung4Chunks.Chunk18
import Erdos647Sparse.Rung4Chunks.Chunk19
import Erdos647Sparse.Rung4Chunks.Chunk20
import Erdos647Sparse.Rung4Chunks.Chunk21
import Erdos647Sparse.Rung4Chunks.Chunk22
import Erdos647Sparse.Rung4Chunks.Chunk23
import Erdos647Sparse.Rung4Chunks.Chunk24
import Erdos647Sparse.Rung4Chunks.Chunk25
import Erdos647Sparse.Rung4Chunks.Chunk26
import Erdos647Sparse.Rung4Chunks.Chunk27

namespace Erdos647Sparse

set_option maxRecDepth 100000
set_option maxHeartbeats 4000000

/-- The 4431 rung-4 survivor classes, flat-encoded:
`i = (pairIdx * 23 + c23) * 29 + c29` over the 41 rung-2b pairs. -/
def rung4Survivors : List ℕ :=
  rung4Ss00 ++ rung4Ss01 ++ rung4Ss02 ++ rung4Ss03 ++ rung4Ss04 ++ rung4Ss05 ++ rung4Ss06 ++ rung4Ss07 ++ rung4Ss08 ++ rung4Ss09 ++ rung4Ss10 ++ rung4Ss11 ++ rung4Ss12 ++ rung4Ss13 ++ rung4Ss14 ++ rung4Ss15 ++ rung4Ss16 ++ rung4Ss17 ++ rung4Ss18 ++ rung4Ss19 ++ rung4Ss20 ++ rung4Ss21 ++ rung4Ss22 ++ rung4Ss23 ++ rung4Ss24 ++ rung4Ss25 ++ rung4Ss26 ++ rung4Ss27



/-- Composed walk soundness: every flat class index is a listed survivor
or a killed class. -/
theorem rung4_killed_or_surv :
    ∀ i : ℕ, i < 27347 → i ∈ rung4Survivors ∨ KilledClass i := by
  intro i hi
  by_cases h00 : i < 1000
  · rcases rung4Walk_sound rung4Walk00 i (by omega) (by omega) with hm | hk
    · exact Or.inl (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ hm)))))))))))))))))))))))))))
    · exact Or.inr hk
  by_cases h01 : i < 2000
  · rcases rung4Walk_sound rung4Walk01 i (by omega) (by omega) with hm | hk
    · exact Or.inl (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_right _ hm)))))))))))))))))))))))))))
    · exact Or.inr hk
  by_cases h02 : i < 3000
  · rcases rung4Walk_sound rung4Walk02 i (by omega) (by omega) with hm | hk
    · exact Or.inl (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_right _ hm))))))))))))))))))))))))))
    · exact Or.inr hk
  by_cases h03 : i < 4000
  · rcases rung4Walk_sound rung4Walk03 i (by omega) (by omega) with hm | hk
    · exact Or.inl (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_right _ hm)))))))))))))))))))))))))
    · exact Or.inr hk
  by_cases h04 : i < 5000
  · rcases rung4Walk_sound rung4Walk04 i (by omega) (by omega) with hm | hk
    · exact Or.inl (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_right _ hm))))))))))))))))))))))))
    · exact Or.inr hk
  by_cases h05 : i < 6000
  · rcases rung4Walk_sound rung4Walk05 i (by omega) (by omega) with hm | hk
    · exact Or.inl (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_right _ hm)))))))))))))))))))))))
    · exact Or.inr hk
  by_cases h06 : i < 7000
  · rcases rung4Walk_sound rung4Walk06 i (by omega) (by omega) with hm | hk
    · exact Or.inl (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_right _ hm))))))))))))))))))))))
    · exact Or.inr hk
  by_cases h07 : i < 8000
  · rcases rung4Walk_sound rung4Walk07 i (by omega) (by omega) with hm | hk
    · exact Or.inl (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_right _ hm)))))))))))))))))))))
    · exact Or.inr hk
  by_cases h08 : i < 9000
  · rcases rung4Walk_sound rung4Walk08 i (by omega) (by omega) with hm | hk
    · exact Or.inl (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_right _ hm))))))))))))))))))))
    · exact Or.inr hk
  by_cases h09 : i < 10000
  · rcases rung4Walk_sound rung4Walk09 i (by omega) (by omega) with hm | hk
    · exact Or.inl (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_right _ hm)))))))))))))))))))
    · exact Or.inr hk
  by_cases h10 : i < 11000
  · rcases rung4Walk_sound rung4Walk10 i (by omega) (by omega) with hm | hk
    · exact Or.inl (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_right _ hm))))))))))))))))))
    · exact Or.inr hk
  by_cases h11 : i < 12000
  · rcases rung4Walk_sound rung4Walk11 i (by omega) (by omega) with hm | hk
    · exact Or.inl (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_right _ hm)))))))))))))))))
    · exact Or.inr hk
  by_cases h12 : i < 13000
  · rcases rung4Walk_sound rung4Walk12 i (by omega) (by omega) with hm | hk
    · exact Or.inl (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_right _ hm))))))))))))))))
    · exact Or.inr hk
  by_cases h13 : i < 14000
  · rcases rung4Walk_sound rung4Walk13 i (by omega) (by omega) with hm | hk
    · exact Or.inl (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_right _ hm)))))))))))))))
    · exact Or.inr hk
  by_cases h14 : i < 15000
  · rcases rung4Walk_sound rung4Walk14 i (by omega) (by omega) with hm | hk
    · exact Or.inl (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_right _ hm))))))))))))))
    · exact Or.inr hk
  by_cases h15 : i < 16000
  · rcases rung4Walk_sound rung4Walk15 i (by omega) (by omega) with hm | hk
    · exact Or.inl (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_right _ hm)))))))))))))
    · exact Or.inr hk
  by_cases h16 : i < 17000
  · rcases rung4Walk_sound rung4Walk16 i (by omega) (by omega) with hm | hk
    · exact Or.inl (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_right _ hm))))))))))))
    · exact Or.inr hk
  by_cases h17 : i < 18000
  · rcases rung4Walk_sound rung4Walk17 i (by omega) (by omega) with hm | hk
    · exact Or.inl (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_right _ hm)))))))))))
    · exact Or.inr hk
  by_cases h18 : i < 19000
  · rcases rung4Walk_sound rung4Walk18 i (by omega) (by omega) with hm | hk
    · exact Or.inl (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_right _ hm))))))))))
    · exact Or.inr hk
  by_cases h19 : i < 20000
  · rcases rung4Walk_sound rung4Walk19 i (by omega) (by omega) with hm | hk
    · exact Or.inl (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_right _ hm)))))))))
    · exact Or.inr hk
  by_cases h20 : i < 21000
  · rcases rung4Walk_sound rung4Walk20 i (by omega) (by omega) with hm | hk
    · exact Or.inl (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_right _ hm))))))))
    · exact Or.inr hk
  by_cases h21 : i < 22000
  · rcases rung4Walk_sound rung4Walk21 i (by omega) (by omega) with hm | hk
    · exact Or.inl (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_right _ hm)))))))
    · exact Or.inr hk
  by_cases h22 : i < 23000
  · rcases rung4Walk_sound rung4Walk22 i (by omega) (by omega) with hm | hk
    · exact Or.inl (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_right _ hm))))))
    · exact Or.inr hk
  by_cases h23 : i < 24000
  · rcases rung4Walk_sound rung4Walk23 i (by omega) (by omega) with hm | hk
    · exact Or.inl (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_right _ hm)))))
    · exact Or.inr hk
  by_cases h24 : i < 25000
  · rcases rung4Walk_sound rung4Walk24 i (by omega) (by omega) with hm | hk
    · exact Or.inl (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_right _ hm))))
    · exact Or.inr hk
  by_cases h25 : i < 26000
  · rcases rung4Walk_sound rung4Walk25 i (by omega) (by omega) with hm | hk
    · exact Or.inl (List.mem_append_left _ (List.mem_append_left _ (List.mem_append_right _ hm)))
    · exact Or.inr hk
  by_cases h26 : i < 27000
  · rcases rung4Walk_sound rung4Walk26 i (by omega) (by omega) with hm | hk
    · exact Or.inl (List.mem_append_left _ (List.mem_append_right _ hm))
    · exact Or.inr hk
  by_cases h27 : i < 27347
  · rcases rung4Walk_sound rung4Walk27 i (by omega) (by omega) with hm | hk
    · exact Or.inl (List.mem_append_right _ hm)
    · exact Or.inr hk
  · omega

/-- Index of a rung-2b survivor pair; 41 for non-survivors (never hit on
candidates). Inverse of `pairAt` on the survivor range. -/
def pairIdxOf : ℕ → ℕ → ℕ
  | 0, 0 => 0
  | 0, 7 => 1
  | 0, 11 => 2
  | 0, 13 => 3
  | 0, 14 => 4
  | 0, 15 => 5
  | 0, 16 => 6
  | 0, 17 => 7
  | 11, 0 => 8
  | 11, 13 => 9
  | 11, 14 => 10
  | 11, 15 => 11
  | 11, 16 => 12
  | 11, 17 => 13
  | 13, 0 => 14
  | 13, 7 => 15
  | 13, 14 => 16
  | 13, 15 => 17
  | 13, 16 => 18
  | 13, 17 => 19
  | 14, 0 => 20
  | 14, 7 => 21
  | 14, 11 => 22
  | 14, 13 => 23
  | 14, 15 => 24
  | 14, 16 => 25
  | 14, 17 => 26
  | 15, 0 => 27
  | 15, 7 => 28
  | 15, 11 => 29
  | 15, 13 => 30
  | 15, 14 => 31
  | 15, 16 => 32
  | 15, 17 => 33
  | 16, 0 => 34
  | 16, 7 => 35
  | 16, 11 => 36
  | 16, 13 => 37
  | 16, 14 => 38
  | 16, 15 => 39
  | 16, 17 => 40
  | _, _ => 41

/-- The rung-4 class filter: the flat-encoded residue class of `n` is a
rung-4 survivor. -/
def classOk4 (n : ℕ) : Bool :=
  inIdx ((pairIdxOf (n % 17) (n % 19) * 23 + n % 23) * 29 + n % 29) rung4Survivors

private theorem rung4_resolve {n p c17 c19 : ℕ} (hn : 100000000000 < n)
    (H : Erdos647Mod.Cand n) (hL : 360360 ∣ n) (hp41 : p < 41)
    (hpa : pairAt p = (c17, c19)) (hpi : pairIdxOf c17 c19 = p)
    (h17 : n % 17 = c17) (h19 : n % 19 = c19) : classOk4 n = true := by
  have h23 : n % 23 < 23 := Nat.mod_lt _ (by norm_num)
  have h29 : n % 29 < 29 := Nat.mod_lt _ (by norm_num)
  rw [classOk4, h17, h19, hpi]
  rcases rung4_killed_or_surv ((p * 23 + n % 23) * 29 + n % 29) (by omega) with hm | hk
  · exact inIdx_of_mem hm
  · exfalso
    have e1 : ((p * 23 + n % 23) * 29 + n % 29) / 667 = p := by omega
    have e2 : ((p * 23 + n % 23) * 29 + n % 29) % 667 / 29 = n % 23 := by omega
    have e3 : ((p * 23 + n % 23) * 29 + n % 29) % 29 = n % 29 := by omega
    exact hk n hn H hL
      (by rw [e1, hpa]; exact h17) (by rw [e1, hpa]; exact h19)
      (by rw [e2]) (by rw [e3])

set_option maxHeartbeats 1600000 in
/-- **Rung 4 headline.** Every candidate `n > 10^11` has its residue class
mod 17·19·23·29 among the 4431 rung-4 survivors. -/
theorem classOk4_of_cand {n : ℕ} (hn : 100000000000 < n)
    (H : Erdos647Mod.Cand n) : classOk4 n = true := by
  have hL : 360360 ∣ n := Erdos647Mod.mod360360_of_cand (by omega) H
  have hp := Erdos647Mod.mod_17_19_of_cand (by omega) H
  simp only [Erdos647Mod.survivors, List.mem_cons, List.not_mem_nil, or_false] at hp
  rcases hp with h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h|h
  · rw [Prod.mk.injEq] at h
    exact rung4_resolve (p := 0) hn H hL (by omega) rfl rfl h.1 h.2
  · rw [Prod.mk.injEq] at h
    exact rung4_resolve (p := 1) hn H hL (by omega) rfl rfl h.1 h.2
  · rw [Prod.mk.injEq] at h
    exact rung4_resolve (p := 2) hn H hL (by omega) rfl rfl h.1 h.2
  · rw [Prod.mk.injEq] at h
    exact rung4_resolve (p := 3) hn H hL (by omega) rfl rfl h.1 h.2
  · rw [Prod.mk.injEq] at h
    exact rung4_resolve (p := 4) hn H hL (by omega) rfl rfl h.1 h.2
  · rw [Prod.mk.injEq] at h
    exact rung4_resolve (p := 5) hn H hL (by omega) rfl rfl h.1 h.2
  · rw [Prod.mk.injEq] at h
    exact rung4_resolve (p := 6) hn H hL (by omega) rfl rfl h.1 h.2
  · rw [Prod.mk.injEq] at h
    exact rung4_resolve (p := 7) hn H hL (by omega) rfl rfl h.1 h.2
  · rw [Prod.mk.injEq] at h
    exact rung4_resolve (p := 8) hn H hL (by omega) rfl rfl h.1 h.2
  · rw [Prod.mk.injEq] at h
    exact rung4_resolve (p := 9) hn H hL (by omega) rfl rfl h.1 h.2
  · rw [Prod.mk.injEq] at h
    exact rung4_resolve (p := 10) hn H hL (by omega) rfl rfl h.1 h.2
  · rw [Prod.mk.injEq] at h
    exact rung4_resolve (p := 11) hn H hL (by omega) rfl rfl h.1 h.2
  · rw [Prod.mk.injEq] at h
    exact rung4_resolve (p := 12) hn H hL (by omega) rfl rfl h.1 h.2
  · rw [Prod.mk.injEq] at h
    exact rung4_resolve (p := 13) hn H hL (by omega) rfl rfl h.1 h.2
  · rw [Prod.mk.injEq] at h
    exact rung4_resolve (p := 14) hn H hL (by omega) rfl rfl h.1 h.2
  · rw [Prod.mk.injEq] at h
    exact rung4_resolve (p := 15) hn H hL (by omega) rfl rfl h.1 h.2
  · rw [Prod.mk.injEq] at h
    exact rung4_resolve (p := 16) hn H hL (by omega) rfl rfl h.1 h.2
  · rw [Prod.mk.injEq] at h
    exact rung4_resolve (p := 17) hn H hL (by omega) rfl rfl h.1 h.2
  · rw [Prod.mk.injEq] at h
    exact rung4_resolve (p := 18) hn H hL (by omega) rfl rfl h.1 h.2
  · rw [Prod.mk.injEq] at h
    exact rung4_resolve (p := 19) hn H hL (by omega) rfl rfl h.1 h.2
  · rw [Prod.mk.injEq] at h
    exact rung4_resolve (p := 20) hn H hL (by omega) rfl rfl h.1 h.2
  · rw [Prod.mk.injEq] at h
    exact rung4_resolve (p := 21) hn H hL (by omega) rfl rfl h.1 h.2
  · rw [Prod.mk.injEq] at h
    exact rung4_resolve (p := 22) hn H hL (by omega) rfl rfl h.1 h.2
  · rw [Prod.mk.injEq] at h
    exact rung4_resolve (p := 23) hn H hL (by omega) rfl rfl h.1 h.2
  · rw [Prod.mk.injEq] at h
    exact rung4_resolve (p := 24) hn H hL (by omega) rfl rfl h.1 h.2
  · rw [Prod.mk.injEq] at h
    exact rung4_resolve (p := 25) hn H hL (by omega) rfl rfl h.1 h.2
  · rw [Prod.mk.injEq] at h
    exact rung4_resolve (p := 26) hn H hL (by omega) rfl rfl h.1 h.2
  · rw [Prod.mk.injEq] at h
    exact rung4_resolve (p := 27) hn H hL (by omega) rfl rfl h.1 h.2
  · rw [Prod.mk.injEq] at h
    exact rung4_resolve (p := 28) hn H hL (by omega) rfl rfl h.1 h.2
  · rw [Prod.mk.injEq] at h
    exact rung4_resolve (p := 29) hn H hL (by omega) rfl rfl h.1 h.2
  · rw [Prod.mk.injEq] at h
    exact rung4_resolve (p := 30) hn H hL (by omega) rfl rfl h.1 h.2
  · rw [Prod.mk.injEq] at h
    exact rung4_resolve (p := 31) hn H hL (by omega) rfl rfl h.1 h.2
  · rw [Prod.mk.injEq] at h
    exact rung4_resolve (p := 32) hn H hL (by omega) rfl rfl h.1 h.2
  · rw [Prod.mk.injEq] at h
    exact rung4_resolve (p := 33) hn H hL (by omega) rfl rfl h.1 h.2
  · rw [Prod.mk.injEq] at h
    exact rung4_resolve (p := 34) hn H hL (by omega) rfl rfl h.1 h.2
  · rw [Prod.mk.injEq] at h
    exact rung4_resolve (p := 35) hn H hL (by omega) rfl rfl h.1 h.2
  · rw [Prod.mk.injEq] at h
    exact rung4_resolve (p := 36) hn H hL (by omega) rfl rfl h.1 h.2
  · rw [Prod.mk.injEq] at h
    exact rung4_resolve (p := 37) hn H hL (by omega) rfl rfl h.1 h.2
  · rw [Prod.mk.injEq] at h
    exact rung4_resolve (p := 38) hn H hL (by omega) rfl rfl h.1 h.2
  · rw [Prod.mk.injEq] at h
    exact rung4_resolve (p := 39) hn H hL (by omega) rfl rfl h.1 h.2
  · rw [Prod.mk.injEq] at h
    exact rung4_resolve (p := 40) hn H hL (by omega) rfl rfl h.1 h.2

end Erdos647Sparse
